### ISSUE TITLE
Migrations fail (postgresql)

### ISSUE THREAD

**Issue by georgy-komarov** [znick/anytask#224]
Команда `python manage.py syncdb --migrate --noinput --settings=settings_production` падает с ошибкой **DatabaseError: relation "mail_message" does not exist** (бд postgresql 10)
[Log](https://pastebin.com/cKQeTGRk)
[Содержимое settings_production.py](https://pastebin.com/S9Sf7XyU)

С базой sqlite3 ошибок не возникает.
[Log](https://pastebin.com/NWmvwy5r)

Пробовал `python manage.py schemamigration users --auto`.
В ответ `Nothing seems to have changed.`

**Comment by znick** [comment]
Сходу не могу сказать почему так :( Подробнее смогу посмотреть только в понедельник-вторник.

**Comment by znick** [comment]
А попробуй сделать

$ python manage.py syncdb --noinput --settings=settings_production
а затем
$ python manage.py migrate --settings=settings_production

**Comment by georgy-komarov** [comment]
Запустил миграции отдельных apps. Вроде помогло.
[Log](https://pastebin.com/7hwgFXe7)

**Comment by georgy-komarov** [comment]
Видимо, postgresql ругается на отсутствие некоторых таблиц при инициализации базы.
Нормальный порядок для postgresql такой (не обращая внимания на ошибки):
`python manage.py syncdb --migrate --noinput --settings=settings_production`
`python manage.py migrate years --settings=settings_production`
`python manage.py migrate groups --settings=settings_production`
`python manage.py migrate courses --settings=settings_production`
`python manage.py migrate tasks --settings=settings_production`
`python manage.py migrate issues --settings=settings_production`
`python manage.py migrate mail --settings=settings_production`
`python manage.py syncdb --migrate --noinput --settings=settings_production`
