### ISSUE TITLE
Ошибка с языком

### ISSUE THREAD

**Issue by IU-dev** [znick/anytask#227]
После развертывания debug-окружения везде на сайте пишет транслитом. Как выбрать нормальный русский язык?

**Comment by georgy-komarov** [comment]
@IU-dev, попробуйте выполнить данные команды
```python manage.py makemessages```
```python manage.py compilemessages```

**Comment by IU-dev** [comment]
Благодарю, заработало. 
Есть еще вопрос.
Возможно ли импортировать какие-то более полные демо данные? Без них в голове путаница в настройке. import_shad.sh в репозитории нет.

**Comment by makhalin** [comment]
`python ./manage.py create_shad < students.xml`
Создает курс с двумя группами
