### ISSUE TITLE
Сделать актуальную версию докер образа для production

### ISSUE THREAD

**Issue by v-goncharenko** [znick/anytask#337]
Нормальный способ развернуть Джангу в прод [описан тут](https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-20-04). Используется nginx + gunicorn под systemd.

@znick что думаешь о таком стеке прода?

В целом можно будет сделать 2 контейнера - для разработки, и для прода. Это послужит базой для дальшейшей автоматизации (кубер или что-то ещё), там всё равно будет под капотом докер использоваться.

**Comment by znick** [comment]
Ну, там ничего про Docker нет, а весь фокус именно в том, как Django завернуть в Docker, чтобы это потом в продакшене работало.

У меня для другого проекта есть такой Dockerfile:
https://gist.github.com/znick/920096496ab2499c1454150d6bfc0daa

Там правда uwsgi и postgres, поэтому просто скопировать не выйдет.

**Comment by v-goncharenko** [comment]
да, я имел в виду, что в dockerfile можно такой подход к развёртке применить, а не deb пакет или что-то ещё.

Для джанги и докера есть такие варианты:
https://docs.docker.com/compose/django/
https://www.caktusgroup.com/blog/2017/03/14/production-ready-dockerfile-your-python-django-app/
https://webdevblog.ru/kak-ispolzovat-django-postgresql-i-docker/

**Comment by znick** [comment]
> https://www.caktusgroup.com/blog/2017/03/14/production-ready-dockerfile-your-python-django-app/

Во, я по этой доке файл выше делал

**Comment by znick** [comment]
Думаю можно считать, что это сделано:
https://github.com/znick/anytask/tree/master/docker
