### ISSUE TITLE
Подключить licensed к actions

### ISSUE THREAD

**Issue by znick** [znick/anytask#365]
Есть такая штука, которая проверяет, что все зависимости имеют правильную лицензии: https://github.com/github/licensed

И есть ее адаптация, чтобы она запускалась в github actions и проверяла каждый PR: https://github.com/marketplace/actions/setup-github-licensed . Нужно подключить ее к этому репозитарию.

**Comment by bcskda** [comment]
В licensed-pip есть баг, что в названиях пакетов ожидаются только латиница и дефисы. Хотя бывают ещё как минимум подчёркивания и точки, из-за чего с anytask-ом оно падает:

https://github.com/bcskda/anytask/runs/2280835856

Сделаю им PR

**Comment by znick** [comment]
Кажется это уже работает
